server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: https://httpbin.org
          order: 0
          predicates:
            - Path=/ip